# Generated by Django 3.2.5 on 2021-07-09 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('mobile_number', models.IntegerField()),
                ('location', models.CharField(max_length=200)),
                ('company_name', models.CharField(max_length=200)),
                ('brand', models.CharField(max_length=200)),
                ('clint_type', models.CharField(max_length=200)),
                ('avg_Revenue', models.IntegerField()),
            ],
        ),
    ]
